Merci d'avoir voté <br /> 
<a href="<?php echo $this->url(array(
                                            'controller'=>'topic',
                                            'action'=>'show',
                                            'topic' => $this->escape($this->topic),
                                            'name'=>null,
                                            'message' => null
                                        )); ?>
                   ">Retour au topic</a>
