<?php $this->headTitle('Utilisateur '.$this->escape($this->user->login)); ?>

<h2><?php echo $this->escape($this->user->login); ?></h2>

<div id="user-info">
    <?php if($this->escape($this->edit)) : ?>
    <a href="<?php echo $this->url(array(
                                           'username'=> $this->escape($this->user->login)
                                        ), 'editUser', true); ?>">Editer mon profil</a><br />
    <?php endif; ?>
    
    
    <img src="<?php echo $this->baseUrl().'/images/'.$this->escape($this->user->avatar) ?>" />
    <br />
    <span class="Bold">Inscrit le <?php echo $this->escape($this->user->date_created); ?></span>
    <br />
    <span class="Bold">Karma : </span><?php echo $this->escape($this->user->karma); ?>
    <br />
    
    <?php if($this->escape($this->user->last_name) != null && $this->escape($this->user->last_name) != '') : ?>
    <span class="Bold">Nom : </span><?php echo $this->escape($this->user->last_name); ?>
    <br />
    <?php endif; ?>
    
    <?php if($this->escape($this->user->first_name) != null && $this->escape($this->user->first_name) != '') : ?>
    <span class="Bold">Prénom : </span><?php echo $this->escape($this->user->first_name); ?>
    <br />
    <?php endif; ?>
    
    <?php if($this->escape($this->user->email) != null && $this->escape($this->user->email) != '') : ?>
    <span class="Bold">E-mail : </span><?php echo $this->escape($this->user->email); ?>
    <br />
    <?php endif; ?>
    
    <?php if($this->escape($this->user->location) != null && $this->escape($this->user->location) != '') : ?>
    <span class="Bold">Lieu : </span><?php echo $this->escape($this->user->location); ?>
    <?php endif; ?>

    <hr />
    <p><a href="<?php echo $this->url(array(
                                'id'=> $this->escape($this->user->id),
                                'username'=> $this->escape($this->user->login)
                            ), 'viewUserTopics', true); ?>">Voir ses <?php echo $this->escape($this->user->amount_topics); ?> sujets</a>
    </p>

    <p><a href="<?php echo $this->url(array(
                                'id'=> $this->escape($this->user->id),
                                'username'=> $this->escape($this->user->login)
                            ), 'viewUserMessages', true); ?>">Voir ses <?php echo $this->escape($this->user->amount_messages); ?> messages</a>
    </p>

    <!--<p>Tags</p>-->

</div>