<?php $this->headTitle('Inscription'); ?>
<div id="register">
    <h3>S'inscrire</h3>
    <?php
    if(isset($this->error))
        echo '<div class="help-error">'.$this->escape($this->error).'</div>';

    if(isset($this->success)):
        echo $this->escape($this->success);
    ?>
    <br />
    Vous pouvez dès à présent <a href="<?php echo $this->url(array(
                                        'module' => 'default',
                                        'controller'=>'user',
                                        'action'=>'login'
                                    )); ?>">vous connecter</a>.
    <?php endif;
    
    if(!isset($this->success))
        echo $this->form;
    ?>
</div>
