<?php $this->headTitle('Créer un sujet'); ?>

<div class="tips">

<p>Avant de poser votre propre question, avez-vous fait une recherche pour voir si une question similaire a déjà été posée ?</p>

<p>Merci de faire votre possible pour poser une question claire, tout en évitant le langage SMS et le maximum de fautes d'orthographe.</p>
<p>Ces conseils permettront de faciliter la lecture de tous et donc d'avoir de meilleures réponses.</p>
    
</div>

<?php echo $this->topicForm;