<?php $this->headTitle($this->escape('Avertir un modérateur'));  ?>

<h3>Avertir un modérateur</h3>

<?php
if(isset($this->message)) :
        echo '<p>'.$this->escape($this->message).'</p>';
?>

<p><a href="#" onclick="window.close();return false;">Fermer</a></p>

<?php
else :
    echo $this->form; 
?>
<div id="topic-main">
    <table id="table-topic">
        <tbody>
            <tr>
                <td id="topic-top">
                    <div id="topic-date">
                        Envoyé le <?php echo $this->escape($this->topic['date']); ?>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div id="topic-content"><?php echo $this->purify($this->topic['message']); ?></div>
                </td>
            </tr>
            <tr>
                <td>
                    <table id="table-vote-author">
                        <tbody>
                                <tr>
                                    <td>
                                        <div class="user-avatar">
                                            <a href="<?php echo $this->url(array(
                                                            'id' => $this->escape($this->topic['userId']),
                                                            'username' => $this->escape($this->topic['login'])
                                                         ), 'showUser', true); ?>">
                                                        <img src="<?php echo $this->baseUrl().'/images/'.$this->escape($this->topic['avatar']); ?>" />
                                            </a>
                                        </div>
                                        <div class="user-details">
                                            <a href="<?php echo $this->url(array(
                                                                'id' => $this->escape($this->topic['userId']),
                                                                'username' => $this->escape($this->topic['login'])
                                                             ), 'showUser', true); ?>"><?php echo $this->escape($this->topic['login']); ?></a>
                                        </div>
                                        
                                    </td>
                                </tr>
                            </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<?php
endif;