<?php 
    $validate = false;
    $this->headTitle($this->escape($this->topic['title'])); 
    $style_reopen_modal_confirm = 'style="display: none;"';
    $style_close_modal_form = 'style="display: none;"';
    $style_nb_reopen_votes = 'style="display: none;"';
    $style_close_motif = 'style="display: none;"';

    if($this->escape($this->topic['status']) == 'closed')
    {
        $style_reopen_modal_confirm = '';
        if($this->escape($this->nb_reopen_votes) > 0)
                $style_nb_reopen_votes = '';
    }
    else
    {
        $style_close_modal_form = '';
        if($this->escape($this->nb_close_votes) > 0)
                $style_close_motif = '';
    }
?>

<div id="show-topic">
    <div id="topic-header">
        <h1>
            <?php 
                if($this->escape($this->topic['status']) == 'closed')
                    echo '<span class="topic-status">[fermé]</span>';
                echo $this->escape($this->topic['title']);
            ?>
        </h1>
    </div>
    
    <div id="topic-main">
        <table id="table-topic">
            <tbody>
                <tr>
                    <td id="topic-top">
                        <div id="topic-date">Envoyé le <?php echo $this->escape($this->topic['date']); ?></div>
                        <?php if($this->escape($this->author) && $this->escape($this->topic['status']) != 'closed'): ?>
                        <div id="edit-topic"><a href="<?php echo $this->url(array(
                                                                'controller'=>'topic',
                                                                'id' => $this->escape($this->topic['topicId'])
                                                            ), 'edit', true); ?>">Editer</a>
                        </div>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div id="topic-content"><?php echo $this->purify($this->topic['message']); ?></div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <table id="table-vote-author">
                            <tbody>
                                <tr>
                                    <td>
                                        <div class="vote-t">
                                            <input type="hidden" value="<?php echo $this->escape($this->topic['topicId']); ?>" />
                                            
                                            <?php echo $this->vote($this->escape($this->topic['topicId']), 'DOWN_TOPIC'); ?>
                                            
                                            <span class="vote-value"><?php echo $this->escape($this->topic['vote']); ?></span>
                                            
                                            <?php echo $this->vote($this->escape($this->topic['topicId']), 'UP_TOPIC'); ?>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="user-avatar">
                                            <a href="<?php echo $this->url(array(
                                                            'id' => $this->escape($this->topic['userId']),
                                                            'username' => $this->escape($this->topic['login'])
                                                         ), 'showUser', true); ?>">
                                                        <img src="<?php echo $this->baseUrl().'/images/'.$this->escape($this->topic['avatar']); ?>" />
                                            </a>
                                        </div>
                                        <div class="user-details">
                                            <a href="<?php echo $this->url(array(
                                                                'id' => $this->escape($this->topic['userId']),
                                                                'username' => $this->escape($this->topic['login'])
                                                             ), 'showUser', true); ?>"><?php echo $this->escape($this->topic['login']); ?></a>
                                        </div>
                                        
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>
                         <div class="topic-tags">
                            <?php foreach($this->tags as $tag) : ?>
                            <div class="tag">
                                <div class="tag-name">
                                    <a href="<?php echo $this->url(array(
                                                                'name'=> $this->escape($tag->name)
                                                            ), 'taggedTopic'); ?>"><?php echo $this->escape($tag->name); ?></a>
                                </div>  
                                <div class="tag-action">
                                <?php echo $this->favoriteTag($this->escape($tag->tag_tagId),$this->escape($this->identity)); ?>
                                </div>
                            </div>    
                            <?php endforeach; ?>
                        </div>
                        <div class="topic-menu">
                            <!-- Lien pour modifier les tags -->
                            <a href="<?php echo $this->url(array(
                                                            'controller'=>'tag',
                                                            'action'=>'retag',
                                                            'topic'=> $this->escape($this->topic['topicId'])
                                                        )); ?>
                                   ">Modifier tags</a>
                            -
                            <!-- Lien pour avertir un modérateur -->
                            <a href="<?php echo $this->url(array(
                                                            'controller'=>'topic',
                                                            'action'=>'alert',
                                                            'topic'=> $this->escape($this->topic['topicId'])
                                                        )); ?>" target="_blank">Avertir un modérateur</a>
                            
                            <?php  if($this->hasAccess($this->module.'_'.$this->controller, 'close')): ?>
                            -
                            <!-- Lien pour voter pour réouvrir / fermer le sujet -->
                            <a href="<?php echo $this->url(array(
                                                            'controller'=>'topic',
                                                            'action'=>'reopen',
                                                            'topic'=> $this->escape($this->topic['topicId'])
                                                        )); ?>" class="reopen-modal-confirm" <?php echo $style_reopen_modal_confirm; ?>>Réouvrir</a>
                                                        
                            <a href="<?php echo $this->url(array(
                                                            'controller'=>'topic',
                                                            'action'=>'close',
                                                            'topic'=> $this->escape($this->topic['topicId'])
                                                        )); ?>" class="close-modal-form" <?php echo $style_close_modal_form; ?>>Fermer</a>
                            <?php endif; ?>
                                                   
                            <?php  if($this->hasAccess($this->module.'_'.$this->controller, 'motifs')): ?>
                            <!-- Lien pour afficher le motifs des votants -->
                            <span class="nb-reopen-votes" <?php echo $style_nb_reopen_votes; ?>>(<?php echo $this->escape($this->nb_reopen_votes); ?>)</span>
        
                            <a href="<?php echo $this->url(array(
                                                            'controller'=>'topic',
                                                            'action'=>'motifs',
                                                            'topic'=> $this->escape($this->topic['topicId'])
                                                        )); ?>" class="close-motif" <?php echo $style_close_motif; ?>>(<?php echo $this->escape($this->nb_close_votes); ?>)</a>
                           <?php endif; ?>
                        </div>
                        <div class="topic-info">
                            <?php 
                                if($this->escape($this->topic['lastEditDate']) != null)
                                    echo 'Edité le '.$this->escape($this->topic['lastEditDate']); 
                            ?>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    
    <div id="messages">
    <?php $i = 0;
    foreach($this->messages as $mess) : ?>
        <a name="<?php echo $this->escape($mess->messageId); ?>"></a>
        <div id="message-<?php echo $this->escape($mess->messageId); ?>" class="message">
            <table class="table-message" <?php if($this->escape($mess->validation)) echo 'id="message-validated"'; ?> >
                <tbody>
                    <tr class="message-top">
                        <td>
                            <div class="message-date">Envoyé le <?php echo $this->escape($mess->messages_date);?></div>

                            <?php if($this->escape($this->author) && ($this->escape($mess->messages_userId) != $this->escape($this->topic['userId']))): ?>
                                <div class="message-validation">
                                <?php if($this->escape($mess->validation)) : $validate = true; ?>
                                    <a class="message-devalidation-link" href="<?php echo $this->url(array(
                                                                        'controller'=>'message',
                                                                        'action'=>'devalidate',
                                                                        'message' => $this->escape($mess->messageId)
                                                                    )); ?>">Annuler validation</a>
                                <?php endif; ?>
                                <?php if(!$validate): ?>
                                        <a class="message-validation-link" href="<?php echo $this->url(array(
                                                                            'controller'=>'message',
                                                                            'action'=>'validate',
                                                                            'message' => $this->escape($mess->messageId)
                                                                        )); ?>">Valider</a>
                                <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div id="message-content"><?php echo $this->purify($mess->content);?></div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <table id="table-vote-author">
                                <tbody>
                                    <tr>
                                        <td>
                                            <div class="vote-m">
                                                <input type="hidden" value="<?php echo $mess->messageId; ?>" />
                                                
                                                <?php echo $this->vote($this->escape($mess->messageId), 'DOWN_MESSAGE'); ?>
                                                
                                                <span class="vote-value"><?php echo $this->escape($mess->messages_vote);?></span>
                                                
                                                <?php echo $this->vote($this->escape($mess->messageId), 'UP_MESSAGE'); ?>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="user-avatar">
                                                <a href="<?php echo $this->url(array(
                                                                'id' => $this->escape($mess->userId),
                                                                'username' => $this->escape($mess->login)
                                                            ), 'showUser', true); ?>">
                                                            <img src="<?php echo $this->baseUrl().'/images/'.$this->escape($mess->avatar); ?>" />
                                                </a>
                                            </div>
                                            <div class="user-details">
                                                <a href="<?php echo $this->url(array(
                                                                    'id' => $this->escape($mess->userId),
                                                                    'username' => $this->escape($mess->login)
                                                                ), 'showUser', true); ?>"><?php echo $this->escape($mess->login); ?></a>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div id="comments-<?php echo $this->escape($mess->messageId); ?>" class="comments">
                                <?php
                                    foreach($this->$i as $comment)
                                    {
                                        echo '<div class="comment">'.nl2br($this->escape($comment->content)).' - Le '.$this->escape($comment->date).' par '.$this->escape($comment->login).'</div>';
                                    }
                                ?>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="comment-link">
                                <a class="comment-link-<?php echo $this->escape($mess->messageId); ?>" href="<?php echo $this->url(array(
                                                    'controller'=>'message',
                                                    'action'=>'comment',
                                                    'message' => $mess->messageId,
                                                    'topic' => $this->topic['topicId']
                                                )); ?>" title="Commenter le message">Ajouter un commentaire
                                </a>
                                <div id="comment-form-<?php echo $this->escape($mess->messageId); ?>" style="display:none;">
                                    <?php 
                                        $this->setFormId($this->commentForm, 'form_comment_'.$mess->messageId);
                                        echo $this->commentForm; 
                                    ?>
                                </div>
                            </div>
                            <div class="message-info">
                            <?php 
                                if($this->escape($mess->lastEditDate) != null)
                                    echo 'Edité le '.$this->escape($mess->lastEditDate); 
                            ?>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table> 
        </div>
    <?php $i++; endforeach; ?>
    </div>
</div>

<?php 
$style_answer_topic = 'style="display: none;"';
$style_dialog_form = 'style="display: none;"';
$style_dialog_motif = 'style="display: none;"';
$style_reopen_form = 'style="display: none;"';

if($this->escape($this->topic['status']) != 'closed')
    $style_answer_topic = '';
?>
<div id="answer-topic" <?php echo $style_answer_topic; ?>>
    <a href="<?php echo $this->url(array(
                                    'topic'=>$this->escape($this->topic['topicId'])
                                ), 'answerTopic', true); ?>">R&eacute;pondre</a>
</div>

<div id="block-quick-answer">
    <?php echo $this->messageForm; ?>
    <a name="answer"></a>
</div>

<?php if($this->hasAccess($this->module.'_'.$this->controller, 'close')): ?>
<div id="dialog-form" title="Voter pour fermer le sujet" <?php echo $style_dialog_form; ?>>
        <?php echo $this->form; ?>
</div>

<div id="dialog-motif" title="Motif des autres votants" <?php echo $style_dialog_motif; ?>>
    <ol>
    <?php
    if($this->escape($this->topic['status']) != 'closed')
    {
        foreach($this->close_motif as $motif)
            echo '<li>'.$this->escape($motif['motif']).' par <strong>'.$this->escape($motif['login']).'</strong></li>';
    }
    ?>
    </ol>
</div>

<div id="dialog-reopen-form" title="Voter pour réouvrir le sujet" <?php echo $style_reopen_form; ?>>
    <input type="hidden" name="topic_id" value="<?php echo $this->escape($this->topic['topicId']); ?>" />
    Vous allez voter pour réouvrir le sujet.<br />
    <?php echo $this->reopenTopicSentence($this->escape($this->nb_reopen_votes)); ?>
</div>

<?php endif; ?>

<?php if($this->hasAccess($this->module.'_message', 'validate')): ?>
    <?php if(!$validate): ?>
        <div id="dialog-validate-message" title="Valider cette réponse">
            Voulez-vous vraiment valider cette réponse ?
            Il vous sera toujours possible d'annuler cette action et de valider une autre réponse.
        </div>
    <?php else: ?>
        <div id="dialog-devalidate-message" title="Annuler la validation">
        Voulez-vous vraiment annuler la validation de cette réponse ?
        </div>
    <?php endif; ?>
<?php endif;
