<table>
    <?php $i=0;
    foreach($this->topics as $topic) : ?>
        <tr>
            <td><a href="<?php echo $this->url(array(
                                            'controller'=>'topic',
                                            'action'=>'show',
                                            'topic'=>$this->escape($topic->topic_topicId),
                                            'name'=>null
                                        )); ?>"><?php echo $this->escape($topic->title);?></a></td>
            <td><?php echo $this->escape($topic->date);?></td>
            <td><?php echo $this->escape($topic->vote);?></td>
        </tr>
        <tr>
            <td>Tags</td>
            <td colspan="2">
                <?php
                foreach($this->$i as $tag) : ?>
                <a href="<?php echo $this->url(array(
                                            'controller'=>'topic',
                                            'action'=>'tag',
                                            'name'=>$this->escape($tag->name)
                                        )); ?>"><?php echo $this->escape($tag->name); ?></a>

                <?php echo $this->favoriteTag($this->escape($tag->tag_tagId), $this->escape($tag->name));
                endforeach; ?>
            </td>
        </tr>
    <?php $i++; endforeach; ?>
</table>
