<?php $this->headTitle('Mentions légales'); ?>

<h1> MENTIONS LEGALES :</h1> 
<p style="text-align: justify"> 
    Conform&eacute;ment aux dispositions des articles 6-III et 19 de la Loi n&deg; 
    2004-575 du 21 juin 2004 pour la Confiance dans l&#39;&eacute;conomie num&eacute;rique, 
    dite L.C.E.N., nous portons &agrave; la connaissance des utilisateurs et visiteurs du 
    site : <a href="http://www.islamine.com" target="_blank">www.islamine.com</a> les 
    informations suivantes :
</p> 
<p style="text-align: justify"> 
    <strong><font size="4">1. Informations l&eacute;gales :</font></strong>
</p> 
<p style="text-align: justify"> 
    Statut du propri&eacute;taire : <strong>particulier</strong><br /> 
    Le Propri&eacute;taire est : <strong>Jérémie Paas</strong><br /> 
    Adresse postale du propri&eacute;taire : 
    <strong>144 Avenue de la Résistance 92350 Le Plessis-Robinson</strong><br /> 
    &nbsp;<br /> 
    Le Responsable de la&nbsp; publication est : <strong>Jérémie Paas</strong><br /> 
    Contact : <strong>postmaster@islamine.com</strong><br />
    
    L&rsquo;hebergeur du site est : <strong>OVH 2 rue Kellermann 59100 Roubaix</strong>
</p> 

<p style="text-align: justify"> 
    <strong><font size="4">2. Pr&eacute;sentation et principe :</font></strong>
</p> <p style="text-align: justify"> Est d&eacute;sign&eacute; ci-apr&egrave;s : 
    <b>Utilisateur</b>, tout internaute se connectant et utilisant le site 
    susnomm&eacute; : <a href="http://www.islamine.com" target="_blank">www.islamine.com</a>.
    <br /> Le site <a href="http://www.islamine.com" target="_blank"><b>www.islamine.com</b></a>
    <b> </b>regroupe un ensemble de services, dans l&#39;&eacute;tat,&nbsp; mis &agrave; 
    la disposition des utilisateurs. Il est ici pr&eacute;cis&eacute; que ces derniers 
    doivent rester courtois et faire preuve de bonne foi tant envers les autres 
    utilisateurs qu&#39;envers le webmaster du site 
    <a href="http://www.islamine.com" target="_blank">www.islamine.com</a>.
    
    <br /> ISLAMINE.COM s&rsquo;efforce de fournir sur le site 
    <a href="http://www.islamine.com" target="_blank">www.islamine.com</a> des 
    informations les plus pr&eacute;cises possibles (sous r&eacute;serve de modifications 
    apport&eacute;es depuis leur mise en ligne), mais ne saurait garantir 
    l&#39;exactitude, la compl&eacute;tude et l&#39;actualit&eacute; des informations 
    diffus&eacute;es sur son site, qu&rsquo;elles soient de son fait ou du fait des tiers 
    partenaires qui lui fournissent ces informations. En cons&eacute;quence, 
    l&#39;utilisateur reconna&icirc;t utiliser ces informations donn&eacute;es (&agrave; 
    titre indicatif, non exhaustives et susceptibles d&#39;&eacute;voluer) sous sa 
    responsabilit&eacute; exclusive.
</p>

<p style="text-align: justify"> 
    <br /> 
    <strong><font size="4">3. Acceptation des termes et conditions :</font></strong>
    <br /> <br /> 
    L&rsquo;utilisation du site 
    <a href="http://www.islamine.com" target="_blank">www.islamine.com</a> implique 
    l&rsquo;acceptation pleine et enti&egrave;re des conditions g&eacute;n&eacute;rales 
    d&rsquo;utilisation&nbsp; d&eacute;crites ci-dessus. Celles-ci sont consultables par 
    l&#39;interm&eacute;diaire d&#39;un lien hypertexte plac&eacute; sur toutes les 
    pages du site <a href="http://www.islamine.com" target="_blank">www.islamine.com</a>. 
    Il est ici rappel&eacute; que les d&eacute;veloppeurs du site 
    <a href="http://www.islamine.com" target="_blank">www.islamine.com</a> gardent 
    trace de l&#39;adresse mail, et de l&#39;adresse IP de tout utilisateur. En 
    cons&eacute;quence, il doit &ecirc;tre conscient qu&#39;en cas d&#39;injonction de 
    l&rsquo;autorit&eacute; judiciaire il peut &ecirc;tre retrouv&eacute; et poursuivi.
</p> 

<p style="text-align: justify"> 
    <strong><font size="4">4. Modification des conditions :</font></strong>
</p> 
<p style="text-align: justify"> 
    ISLAMINE.COM se r&eacute;serve le droit, &agrave; tout moment, de modifier, 
    compl&eacute;ter, enlever ou ajouter, ce sans pr&eacute;avis, tout ou partie des 
    pr&eacute;sentes conditions d&#39;utilisation du site 
    <a href="http://www.islamine.com" target="_blank">www.islamine.com</a>, aussi les 
    utilisateurs du site 
    <a href="http://www.islamine.com" target="_blank">www.islamine.com</a> 
    sont&nbsp;invit&eacute;s &agrave; les consulter de mani&egrave;re 
    r&eacute;guli&egrave;re, car elles s&#39;imposent &agrave; eux sans aucune 
    r&eacute;serve. L&rsquo;utilisateur est r&eacute;put&eacute; les accepter sans 
    r&eacute;serve et s&rsquo;y r&eacute;f&eacute;rer r&eacute;guli&egrave;rement pour 
    prendre connaissance des modifications. Le site 
    <a href="http://www.islamine.com" target="_blank">www.islamine.com</a> se 
    r&eacute;serve aussi le droit de c&eacute;der, transf&eacute;rer, ce sans 
    pr&eacute;avis, les droits et/ou obligations des pr&eacute;sentes CGU et mentions 
    l&eacute;gales. En continuant &agrave; utiliser les Services du site 
    <a href="http://www.islamine.com" target="_blank">www.islamine.com</a> , 
    l&rsquo;utilisateur reconna&icirc;t accepter les modifications des conditions 
    g&eacute;n&eacute;rales d&#39;utilisation qui seraient intervenues.
</p> 

<p style="text-align: justify"> 
    &nbsp;<br /> 
    <strong><font size="4">5. Limitation de responsabilit&eacute; :</font></strong>
    <br /> <br /> 
    Le site <a href="http://www.islamine.com" target="_blank">www.islamine.com</a> ne 
    saurait &ecirc;tre tenu responsable des erreurs typographiques ou inexactitudes 
    apparaissant sur le service, ou de quelques dommages subis r&eacute;sultant 
    de son utilisation. L&rsquo;utilisateur reste responsable de son &eacute;quipement 
    et de son utilisation, de m&ecirc;me il supporte seul les co&ucirc;ts directs ou 
    indirects suite &agrave; sa connexion &agrave; Internet.
    <br /> Le site <a href="http://www.islamine.com" target="_blank">www.islamine.com</a>
    utilise la technologie java script. Pour acc&eacute;der &agrave; l&#39;ensemble du 
    site <a href="http://www.islamine.com" target="_blank">www.islamine.com</a>, 
    l&rsquo;utilisateur s&rsquo;engage &agrave; utiliser un mat&eacute;riel r&eacute;cent, 
    ne contenant pas de virus et avec les mises &agrave; jour faites de son 
    navigateur.&nbsp; L&rsquo;utilisateur d&eacute;gage la responsabilit&eacute; de 
    <a href="http://www.islamine.com" target="_blank">www.islamine.com</a> pour tout 
    pr&eacute;judice qu&rsquo;il pourrait subir ou faire subir, directement ou 
    indirectement, du fait de l&#39;utilisation des services propos&eacute;s. Seule 
    la responsabilit&eacute; de l&rsquo;utilisateur est engag&eacute;e par 
    l&rsquo;utilisation du service propos&eacute; et celui-ci d&eacute;gage 
    express&eacute;ment le site 
    <a href="http://www.islamine.com" target="_blank">www.islamine.com</a> de toute 
    responsabilit&eacute; vis &agrave; vis de tiers.
    <br /> Tout contenu (texte, photos, dessins,...) &eacute;mis par 
    l&#39;interm&eacute;diaire de l&#39;espace contact ou tout autre espace interactif 
    mis &agrave; la la disposition des utilisateurs et&nbsp;non conforme aux 
    dispositions l&eacute;gales et r&eacute;glementaires en vigueur et applicable 
    en France, notamment atteintes aux droits de la personnalit&eacute; de tiers 
    (diffamation, injures, atteinte &agrave; la vie priv&eacute;e,...), acte de 
    concurrence d&eacute;loyale, atteinte &agrave; l&#39;ordre public et aux bonnes 
    m&oelig;urs (incitation &agrave; la haine raciale, n&eacute;gationnisme, 
    r&eacute;visionnisme, pornographique,...) sera, sans mise en demeure 
    pr&eacute;alable, supprim&eacute; sur le champ. Dans une telle situation, 
    Jérémie &nbsp;Paas propri&eacute;taire du site 
    <a href="http://www.islamine.com" target="_blank">www.islamine.com</a> se 
    r&eacute;serve la possibilit&eacute; de mettre en cause la responsabilit&eacute; 
    civile et/ou p&eacute;nale de l&rsquo;utilisateur incrimin&eacute;.
</p> 

<p style="text-align: justify"> 
    <br /> 
    <strong><font size="4">6. Propri&eacute;t&eacute; intellectuelle :</font></strong>
    <br /> <br /> 
    ISLAMINE.COM est propri&eacute;taire exclusif de tous les droits de 
    propri&eacute;t&eacute; intellectuelle ou d&eacute;tient les droits d&rsquo;usage 
    sur tous les &eacute;l&eacute;ments accessibles sur le site, tant sur la structure 
    que sur les textes, images, graphismes, logo, ic&ocirc;nes, sons, logiciels&hellip;
    <br /> Toute reproduction totale ou partielle du site 
    <a href="http://www.islamine.com" target="_blank">www.islamine.com</a>, 
    repr&eacute;sentation, modification, publication, adaptation totale ou partielle 
    de l&#39;un quelconque de ces &eacute;l&eacute;ments, quel que soit le moyen ou 
    le proc&eacute;d&eacute; utilis&eacute;, est interdite, sauf autorisation 
    &eacute;crite pr&eacute;alable.
    A d&eacute;faut elle sera consid&eacute;r&eacute;e comme constitutive 
    d&rsquo;une contrefa&ccedil;on et passible de poursuite conform&eacute;ment 
    aux dispositions des articles L.335-2 et suivants du Code de Propri&eacute;t&eacute; 
    Intellectuelle.
</p> 

<p style="text-align: justify"> 
    <br /> 
    <strong><font size="4">7. Liens hypertextes et cookies :</font></strong>
    <br /> <br /> 
    Le site <a href="http://www.islamine.com" target="_blank">www.islamine.com</a> 
    contient un certain nombre de liens hypertextes vers d&rsquo;autres sites 
    (partenaires, informations &hellip;) mis en place avec l&rsquo;autorisation de 
    Jérémie Paas. Cependant, ISLAMINE.COM n&rsquo;a pas la possibilit&eacute; de 
    v&eacute;rifier l&#39;ensemble du contenu des sites ainsi visit&eacute;s&nbsp;et 
    d&eacute;cline donc toute responsabilit&eacute; de ce fait quand aux risques 
    &eacute;ventuels de contenus illicites.<br /> L&rsquo;utilisateur est inform&eacute; 
    que lors de ses visites sur le site 
    <a href="http://www.islamine.com" target="_blank">www.islamine.com</a>, un ou 
    des cookies sont susceptibles de s&rsquo;installer automatiquement sur son 
    ordinateur par l&#39;interm&eacute;diaire de son logiciel de navigation. Un 
    cookie est un bloc de donn&eacute;es qui ne permet pas d&#39;identifier 
    l&#39;utilisateur, mais qui enregistre des informations relatives &agrave; 
    la navigation de celui-ci sur le site.&nbsp;<br /> Le param&eacute;trage du 
    logiciel de navigation permet d&rsquo;informer de la pr&eacute;sence de cookie 
    et &eacute;ventuellement, de la refuser de la mani&egrave;re d&eacute;crite 
    &agrave; l&rsquo;adresse suivante : <a href="http://www.cnil.fr">www.cnil.fr</a>. 
    L&rsquo;utilisateur peut toutefois configurer le navigateur de son ordinateur pour 
    refuser l&rsquo;installation des cookies, sachant que le refus d&#39;installation 
    d&#39;un cookie peut entra&icirc;ner l&rsquo;impossibilit&eacute; 
    d&rsquo;acc&eacute;der &agrave; certains services. Pour tout bloquage des cookies, 
    tapez dans votre moteur de recherche : bloquage des cookies sous IE ou firefox et 
    suivez les instructions en fonction de votre version.
    <br /> <br /> <br /> 
    
    <strong><font size="4">8. Protection des biens et des personnes - gestion des donn&eacute;es personnelles :</font></strong>
    <br /> <br /> 
    En France, les donn&eacute;es personnelles sont notamment prot&eacute;g&eacute;es 
    par la loi n&deg; 78-87 du 6 janvier 1978, la loi n&deg; 2004-801 du 6 ao&ucirc;t 
    2004, l&#39;article L. 226-13 du Code p&eacute;nal et la Directive Europ&eacute;enne 
    du 24 octobre 1995.
</p> 

<p style="text-align: justify"> 
    Sur le site 
    <a href="http://www.islamine.com" target="_blank">www.islamine.com</a>, 
    ISLAMINE.COM ne collecte des informations personnelles 
    (suivant l&#39;article 4 loi n&deg;78-17 du 06 janvier 1978) relatives &agrave; 
    l&#39;utilisateur que pour le besoin de certains services propos&eacute;s par 
    le site <a href="http://www.islamine.com" target="_blank">www.islamine.com</a>. 
    L&#39;utilisateur fournit ces informations en toute connaissance de cause, 
    notamment lorsqu&#39;il proc&egrave;de par lui-m&ecirc;me &agrave; leur saisie. 
    Il est alors pr&eacute;cis&eacute; &agrave; l&#39;utilisateur du site 
    <a href="http://www.islamine.com" target="_blank">www.islamine.com</a> 
    l&rsquo;obligation ou non de fournir ces informations.
    <br /> Conform&eacute;ment 
    aux dispositions des articles 38 et suivants de la loi 78-17 du 6 janvier 1978 
    relative &agrave; l&rsquo;informatique, aux fichiers et aux libert&eacute;s, 
    tout utilisateur dispose d&rsquo;un droit d&rsquo;acc&egrave;s, de rectification, 
    de suppression et d&rsquo;opposition aux donn&eacute;es personnelles le concernant. 
    Pour l&rsquo;exercer, adressez votre demande &agrave; 
    <a href="http://www.islamine.com" target="_blank">www.islamine.com</a> par 
    email : <strong><a href="mailto:islamine@gmail.com?subject=Contact à partir des mentions légales via le site www.islamine.com">islamine@gmail.com</a></strong> 
    ou&nbsp;par &eacute;crit&nbsp;d&ucirc;ment sign&eacute;e, accompagn&eacute;e 
    d&rsquo;une copie du titre d&rsquo;identit&eacute; avec signature du titulaire de 
    la pi&egrave;ce, en pr&eacute;cisant l&rsquo;adresse &agrave; laquelle la 
    r&eacute;ponse doit &ecirc;tre envoy&eacute;e.
</p> 

<p style="text-align: justify"> 
    Aucune information personnelle de l&#39;utilisateur du site 
    <a href="http://www.islamine.com" target="_blank">www.islamine.com</a> n&#39;est 
    publi&eacute;e &agrave; l&#39;insu de l&#39;utilisateur, &eacute;chang&eacute;e, 
    transf&eacute;r&eacute;e, c&eacute;d&eacute;e ou vendue sur un support quelconque 
    &agrave; des tiers. Seule l&#39;hypoth&egrave;se du rachat du site 
    <a href="http://www.islamine.com" target="_blank">www.islamine.com</a> et de ses 
    droits autorise ISLAMINE.COM &agrave; transmettre les dites informations 
    &agrave; l&#39;&eacute;ventuel acqu&eacute;reur qui serait &agrave; son tour 
    tenu&nbsp;&agrave; la m&ecirc;me obligation de conservation et de modification 
    des donn&eacute;es vis &agrave; vis de l&#39;utilisateur du site 
    <a href="http://www.islamine.com" target="_blank">www.islamine.com</a>.
    <br /> Le site <a href="http://www.islamine.com" target="_blank">www.islamine.com</a> 
    est d&eacute;clar&eacute; &agrave; la CNIL sous le num&eacute;ro .
</p> 

<p style="text-align: justify"> 
    Les bases de donn&eacute;es sont prot&eacute;g&eacute;es par les dispositions de 
    la loi du 1er juillet 1998 transposant la directive 96/9 du 11 mars 1996 relative 
    &agrave; la protection juridique des bases de donn&eacute;es.
</p> 

<p style="text-align: justify"> 
    <strong>
        <font size="4">9. Loi applicable et juridiction comp&eacute;tente :</font>
    </strong>
    <br /> <br /> 
    Les pr&eacute;sentes Conditions G&eacute;n&eacute;rales d&#39;Utilisation et la 
    relation de l&#39;utilisateur avec le site 
    <a href="http://www.islamine.com" target="_blank">www.islamine.com</a> en vertu 
    de ces Conditions G&eacute;n&eacute;rales d&#39;Utilisation sont r&eacute;gies 
    par le droit Fran&ccedil;ais. L&rsquo;utilisateur ainsi que 
    <a href="http://www.islamine.com" target="_blank">www.islamine.com</a> acceptent
    de se soumettre &agrave; la comp&eacute;tence exclusive des tribunaux 
    Fran&ccedil;ais en cas de litige r&eacute;sultant de ces conditions 
    g&eacute;n&eacute;rales d&#39;utilisation.
</p>
