<?php $this->headTitle('FAQ'); 
?>
<div id="faq">
   <h2>Foire aux questions</h2>
   
   <h3>Comment fonctionnent les bibliothèques de documents ?</h3>
   <p>
       Chaque utilisateur possède la propre bibliothèque et peut y ajouter des documents
       pour pouvoir les retrouver quand bon lui semble.
   </p>
   <p>
       Lors de la création d'un document vous êtes amenés à préciser sa source. Cela peut être
       une personne, une site, une certaine école, etc.
       Vous devez aussi indiquer des mots-clés en rapport avec le document pour qu'il soit
       plus facilement répertorié et trouvable.
       Vous pouvez aussi choisir de partager ce document avec les autres en choisissant de le
       publier. Vous pouvez modifier toutes les informations sur un document plus tard si
       vous le souhaitez.
   </p>
   <p>
       Une fois un document rendu public, les autres utilisateurs peuvent voter, 
       le mettre en favoris ou le commenter.
   </p>

    <h3>Qu'est-ce que le karma ?</h3>
    <p>
        Le karma est un reflet de la confiance que vous accorde la communauté. Plus vous
        posterez des contenus intéressants, en évitant de tomber dans la dérive ou dans 
        le haram, plus vous aurez de chance de gagner du karma.
    </p>

    <h3>Comment gagner des points de karma ?</h3>
    <p>
        Vous gagnez des points de karma lorsque les autres votent positivement sur l'un de
        vos message. Vous pouvez aussi en gagner en validant une réponse à vos sujets.
        Plus vous aurez un karma élevé plus vous gagnerez des privilèges pour effectuer des
        actions sur le forum. Les membres avec un karma suffisamment élevé peuvent avoir
        accès aux outils de modération.
    </p>

    <h3>Quels sont les privilèges à gagner ?</h3>
    <p>
        Il y a différents privilèges. Pour plus de détails rendez vous sur la 
        page correspondante.
    </p>
</div>

