<?php $this->headTitle('FAQ'); 
?>
<div id="faq">
   <h2>Foire aux questions</h2>
   
   <h3>Comment fonctionnent les bibliothèques de documents ?</h3>
   <p>
       Chaque utilisateur possède la propre bibliothèque et peut y ajouter des documents
       pour pouvoir les retrouver quand bon lui semble.
   </p>
   <p>
       Lors de la création d'un document vous êtes amenés à préciser sa source. Cela peut être
       une personne, une site, une certaine école, etc.
       Vous devez aussi indiquer des mots-clés en rapport avec le document pour qu'il soit
       plus facilement répertorié et trouvable.
       Vous pouvez aussi choisir de partager ce document avec les autres en choisissant de le
       publier. Il est possible de modifier toutes les informations concernant un document plus tard si
       vous le souhaitez.
   </p>
   <p>
       Une fois un document rendu public, les autres utilisateurs peuvent voter, 
       le mettre en favoris ou le commenter.
   </p>
   
   <h3>Qu'est-ce que les évènements ?</h3>
   <p>
       Un évènement correspond à n'importe quel rendez-vous islamique. Il peut s'agir d'une
       conférence, de cours sur l'Islam, de réunions, etc.
   </p>

    <h3>Qu'est-ce que le karma ?</h3>
    <p>
        Le karma est un reflet de la confiance que vous accorde la communauté. Plus vous
        posterez des contenus intéressants, en évitant de tomber dans la dérive ou dans 
        le haram, plus vous aurez de chance de gagner du karma.
    </p>

    <h3>Comment gagner des points de karma ?</h3>
    <p>
        Vous gagnez des points de karma (+5) lorsque les autres votent positivement sur l'un de
        vos document.
        Attention, un vote négatif entrainne une chute de 2 points, mais pour cela, la personne
        qui vote devra sacrifier un point pour éviter les abus.
    </p>
    <p>
        Plus vous aurez un karma élevé plus vous gagnerez des privilèges.
        Si ce système fonctionne il sera étendu 
        (il y aura d'autres manières de gagner du karma).
    </p>

    <h3>Quels sont les privilèges à gagner ?</h3>
    <p>
        Pour l'instant il n'y aucun privilège à gagner. Si le système de karma fonctionne
        ils seront ajoutés pour permettre aux utilisateurs d'effectuer certaines actions
        en fonction de leur niveau de karma.
    </p>
</div>

