<div id="welcome-content">
    <div class="post">
        <h1>Bienvenue sur Islamine, le site qui vous permet de conserver
            les contenus sur l'Islam qui vous plaisent (articles, hadiths, vidéos, conférences...).</h1>
        <h1>Vous pouvez aussi découvrir ce que les autres ont à partager, alors
            n'hésitez pas !
        </h1>
        
        <h1 class="work"><a href="<?php echo $this->url(array(
                                    ), 'faq', true) ?>">Comment ça marche ?</a></h1>
    </div>
</div>

<?php if(!$this->escape($this->isUserConnected)) : ?>
<div class="index-register">
    <a class="btn btn-large btn-success" 
       href="<?php echo $this->url(array(
                                    'controller' => 'user',
                                    'action' => 'register'
                                ), 'default', true) ?>">S'inscrire</a>
</div>
<?php endif; ?>

<div class="carousel-container">
  <div id="carousel">
    <div class="carousel-feature">
      <a><img class="carousel-image" alt="Image Caption" src="images/allahsunset.jpg" /></a>
      <div class="carousel-caption">
        <p>
            Un peu de science éloigne de Dieu, beaucoup de science y ramène - 
            <span class="carousel-caption-author">Louis Pasteur</span>
        </p>
      </div>
    </div>
    <div class="carousel-feature">
      <a><img class="carousel-image" alt="Image Caption" src="images/aurore.jpg" /></a>
    </div>
    <div class="carousel-feature">
      <a><img class="carousel-image" alt="Image Caption" src="images/ciel-rouge.jpg" /></a>
      <div class="carousel-caption">
        <p>
          Un honnête homme armé de tout le savoir dont nous disposons actuellement ne 
          pourrait pas aboutir à une autre conclusion : dans un sens, l'origine de la 
          vie apparaît presque aujourd'hui comme un miracle -
          <span class="carousel-caption-author">Francis Crick</span>
        </p>
      </div>
    </div>
    <div class="carousel-feature">
      <a><img class="carousel-image" alt="Image Caption" src="images/nature.jpg" /></a>
      <div class="carousel-caption">
        <p>
            L'hypothèse énoncant que la vie ait pu apparaître spontanément sur la 
            Terre est encore plus improbable que celle affirmant qu'une tornade balayant 
            au hasard les éléments d'une décharge puisse les assembler pour créer un 
            boeing 747 en parfait état de marche -
            <span class="carousel-caption-author">Fred Hoyle</span>
        </p>
      </div>
    </div>
    <div class="carousel-feature">
      <a><img class="carousel-image" alt="Image Caption" src="images/galaxie.jpg" /></a>
      <div class="carousel-caption">
        <p>
            Et Il vous a assujetti tout ce qui est dans les cieux et sur la terre, 
            le tout venant de Lui. Il y a là des signes pour des gens qui réfléchissent -
            <span class="carousel-caption-author">Sourate 15, verset 13</span>
        </p>
      </div>
    </div>
  </div>

  <div id="carousel-left"><img src="images/arrow-left.png" /></div>
  <div id="carousel-right"><img src="images/arrow-right.png" /></div>
</div>