<?php $this->headTitle('Accueil'); ?>

<div id="welcome-content">
    <div class="post">
        <h1>Bienvenue sur Islamine, le site qui vous permet de conserver
            les contenus sur l'Islam qui vous plaisent (articles, hadiths, vidéos, conférences...).</h1>
        <h1>Vous pouvez aussi découvrir ce que les autres ont à partager, alors
            n'hésitez pas !
        </h1>
        
        <h1 class="work"><a href="<?php echo $this->url(array(
                                    ), 'faq', true) ?>">Comment ça marche ?</a></h1>
    </div>
</div>

<div class="carousel-container">
  <div id="carousel">
    <div class="carousel-feature">
      <a><img class="carousel-image" alt="Image Caption" src="images/allahsunset.jpg" /></a>
      <div class="carousel-caption">
        <p>
            Un peu de science éloigne de Dieu, beaucoup de science y ramène - 
            <span class="carousel-caption-author">Louis Pasteur</span>
        </p>
      </div>
    </div>
    <div class="carousel-feature">
      <a><img class="carousel-image" alt="Image Caption" src="images/aurore.jpg" /></a>
    </div>
    <div class="carousel-feature">
      <a><img class="carousel-image" alt="Image Caption" src="images/ciel-rouge.jpg" /></a>
      <div class="carousel-caption">
        <p>
          Images can be placed here as well.
        </p>
      </div>
    </div>
    <div class="carousel-feature">
      <a><img class="carousel-image" alt="Image Caption" src="images/nature1.jpg" /></a>
    </div>
    <div class="carousel-feature">
      <a><img class="carousel-image" alt="Image Caption" src="images/sample5.jpg" /></a>
      <div class="carousel-caption">
        <p>
          The background color of the caption area can be changed using CSS. The opacity can be changed in the options, but it will also change the opacity of the text.
        </p>
      </div>
    </div>
  </div>

  <div id="carousel-left"><img src="images/arrow-left.png" /></div>
  <div id="carousel-right"><img src="images/arrow-right.png" /></div>
</div>

<!--<div id="index-icons">
    <table>
        <tr>
            <td>
                <a href="<?php echo $this->url(array(
                                    ), 'docList', true) ?>">
                    <p>
                        Documents publiés
                        <br />
                        <span class="detail">(<?php echo $this->escape($this->documentsAmount); ?>)</span>
                    </p>
                </a>
            </td>
            <td>
                <a href="<?php echo $this->url(array(
                                        'controller' => 'event',
                                        'action' => 'index'
                                    ), 'default', true) ?>">
                <p>
                    Evènements
                    <br />
                    <span class="detail">(<?php echo $this->escape($this->eventsAmount); ?> ce mois-ci)</span>
                </p>
                </a>
            </td>
            <td>
                <a href="<?php echo $this->url(array(
                                        'controller' => 'user',
                                        'action' => 'list'
                                    ), 'default', true) ?>">
                
                    <p>
                        Membres
                        <br />
                        <span class="detail">(<?php echo $this->escape($this->usersAmount); ?>)</span>
                    </p>
                </a>
            </td>
        </tr>
    </table>
</div>-->

<?php if(!$this->escape($this->isUserConnected)) : ?>
<div class="index-register">
    <a class="btn btn-large btn-success" 
       href="<?php echo $this->url(array(
                                    'controller' => 'user',
                                    'action' => 'register'
                                ), 'default', true) ?>">S'inscrire</a>
</div>
<?php endif; ?>

