<?php $this->headTitle('Accueil'); ?>

<div id="welcome-content">
    <div class="post">
        <h1>Bienvenue sur Islamine, le site qui vous permet de ne plus 
        perdre les contenus que vous trouvez intéressant sur l'islam !</h1>
        <h1>Vous pouvez aussi découvrir les documents que les autres personnes veulent
        bien partager.</h1>
    </div>
</div>

<div id="index-icons">
    <table>
        <tr>
            <td>
                <a href="<?php echo $this->url(array(
                                    ), 'docList', true) ?>">
                    <p>
                        Documents publiés
                        <br />
                        <span class="detail">(<?php echo $this->escape($this->documentsAmount); ?>)</span>
                    </p>
                </a>
            </td>
            <td>
                <a href="<?php echo $this->url(array(
                                        'controller' => 'event',
                                        'action' => 'index'
                                    ), 'default', true) ?>">
                <p>
                    Evènements
                    <br />
                    <span class="detail">(<?php echo $this->escape($this->eventsAmount); ?> ce mois-ci)</span>
                </p>
                </a>
            </td>
            <td>
                <a href="<?php echo $this->url(array(
                                        'controller' => 'user',
                                        'action' => 'list'
                                    ), 'default', true) ?>">
                
                    <p>
                        Membres
                        <br />
                        <span class="detail">(<?php echo $this->escape($this->usersAmount); ?>)</span>
                    </p>
                </a>
            </td>
        </tr>
    </table>
</div>

<?php if(!$this->escape($this->isUserConnected)) : ?>
<div class="index-register">
    <a class="btn btn-large btn-success" 
       href="<?php echo $this->url(array(
                                    'controller' => 'user',
                                    'action' => 'register'
                                ), 'default', true) ?>">S'inscrire</a>
</div>
<?php endif; ?>

