<table id="tags-table">
<?php foreach (array_chunk($this->tags, 4) as $row) : ?>
    <tr>
        <?php foreach ($row as $tag) : ?>
        <td>
            <div class="tag">
                <div class="tag-name">
                    <a href="<?php echo $this->url(array(
                                        'name' => $this->escape($tag['name'])
                                    ), 'taggedTopic', true); ?>"><?php echo $this->escape($tag['name']); ?>
                    </a>
                </div>  
            </div> 
            &nbsp; x <?php echo $this->escape($tag['amount']); ?>
        </td>
        <?php endforeach; ?>
    </tr>
<?php endforeach; ?>
</table>