<?php $this->headTitle($this->escape('Changer mots-clés'));  ?>

<div class="tips">
    <p>Vous vous apprêtez à modifier les mots-clés d'un sujet.</p>
    <p>
    Merci de prendre en compte cette liste avant de valider vos modifications :
    <ol>
        <li>Veillez à utiliser des mots-clés qui existent déjà si possible</li>
        <li>Si plusieurs mots-clés existants correspondent à votre idée, préférez celui qui a été utilisé le plus de fois</li>
        <li>Veillez à utiliser des mots-clés qui correspondent au texte du sujet.</li>
    </ol>
    </p>
</div>


<?php echo $this->form;
