<?php $this->headTitle('FAQ'); 
?>
<div id="faq">
   <h2>Foire aux questions</h2>

    <h3>Comment fonctionne ce forum ?</h3>
    <p>
        Ce forum n'est pas divisé en section comme la plupart de ceux que vous pouvez 
        rencontrer sur internet.
    </p>
    <p>
        En effet, tous les sujets sont regroupés, mais ils se distinguent les uns par
        rapport aux autres avec des mots-clés. Vous pouvez lister tous les sujets à propos
        d'un mot-clé en cliquant dessus. Il est aussi possible de mettre des mots-clés en
        favoris pour distinguer plus facilement les sujets qui sont susceptibles de vous
        intéresser.
    </p>
    <p>
        Les utilisateurs peuvent voter (à partir d'un certain niveau de karma) sur les
        sujets et les messages. Les votes positifs permettent de donner du crédit aux bonnes
        questions/réponses. A l'inverse, voter négativement montre aux autres qu'il faut 
        faire attention quant à la qualité du texte écrit.
        <br />
        Ce système est fait pour encourager les réponses de qualité.
    </p>

    <h3>Qu'est-ce que le karma ?</h3>
    <p>
        Le karma est un reflet de la confiance que vous accorde la communauté. Plus vous
        ferez des messages de qualité, en évitant de tomber dans la dérive ou dans le haram,
        plus vous aurez de chance de gagner du karma.
    </p>

    <h3>Comment gagner des points de karma ?</h3>
    <p>
        Vous gagnez des points de karma lorsque les autres votent positivement sur l'un de
        vos message. Vous pouvez aussi en gagner en validant une réponse à vos sujets.
        Plus vous aurez un karma élevé plus vous gagnerez des privilèges pour effectuer des
        actions sur le forum. Les membres avec un karma suffisamment élevé peuvent avoir
        accès aux outils de modération.
    </p>

    <h3>Quels sont les privilèges à gagner ?</h3>
    <p>
        Il y a différents privilèges. Pour plus de détails rendez vous sur la page
        correspondante.
    </p>

    <h3>Pourquoi il y a-t-il des sujets fermés ?</h3>
    <p>
        Les sujets peuvent être fermés suite a 7 votes de membres différents sur un même
        sujet. Il peut etre réouvert s'il obtient de nouveau 7 votes pour le réouvrir.
    </p>

    <h3>Comment faire pour créer des mots-clés ?</h3>
    <p>
        Créer des mots-clés nécessite 700 points de karma. Cette restriction a été faite pour
        éviter d'avoir une multitude de mots-clés pour un seul thème. Par exemple 'Al-Fiqh'
        et 'Fiqh' qui pourraient être regroupés. En ce sens, les sujets seront moins
        dispersés et plus facilement accessibles lors d'une recherche par mot-clé.
    </p>

    <h3>Pourquoi je ne peux pas supprimer mes messages ou mes sujets ?</h3>
    <p>
        Pour supprimer ses propres messages ou sujets il faut acquérir le privilège
        adéquat qui nécessite 250 points de karma.
    </p>

    <h3>Quelle est la différence entre un commentaire et une réponse ?</h3>
    <p>
        Les commentaires sont là pour demander des détails ou donner son avis.
        Ils ont une taille limite de 500 caractères, pour éviter des discussions.
    </p>
    <p>
        Le but des commentaires est plutot d'écrire un texte court alors que les réponses
        apportent vraiment un plus à la discussion.
    </p>
</div>

