<?php $this->headTitle($this->escape($this->title)); ?>

<div id="topics-top">
    <div id="topic-container-top">
        Sujet et mots clés
    </div>
    <div id="topic-date-top">
        Date
    </div>
    <div id="topic-vote-response-top">
        Votes / Réponses
    </div>
</div>

<div id="topics">
    <?php $i=0;
    foreach($this->topics as $topic) : 
    ?>
        <div <?php echo $this->topicContainerClass($topic); ?>>
            <div class="topic-container">
                <div class="topic-subject">
                    <?php if($this->escape($topic->status) == 'closed')
                            echo '[fermé]';
                    ?>
                    <a href="<?php echo $this->url(array(
                                            'controller'=>'topic',
                                            'action'=>'show',
                                            'topic'=>$this->escape($topic->topicId)
                                        )); ?>"><?php echo $this->escape($topic->title);?></a></div>
                <div class="tags">
                    <?php
                    foreach($this->$i as $tag) : ?>
                    <div class="tag">
                        <div class="tag-name">
                            <a href="<?php echo $this->url(array(
                                                'controller'=>'topic',
                                                'action'=>'tag',
                                                'name'=> $this->escape($tag->name)
                                            )); ?>"><?php echo $this->escape($tag->name); ?></a>
                        </div>  
                        <div class="tag-action">
                            <?php echo $this->favoriteTag($this->escape($tag->tag_tagId)); ?>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
                <div class="topic-author">
                    <a href="<?php echo $this->url(array(
                                                'module' => 'default',
                                                'controller'=>'user',
                                                'action'=>'index',
                                                'username'=> $this->escape($topic['login'])
                                            ), null, true); ?>"><?php echo $this->escape($topic->login); ?></a>
                </div>
            </div>
            <div class="topic-stats">
                <div class="vote-response-block">
                <div class="topic-vote"><?php echo $this->escape($topic->vote);?> votes</div>
                <div class="topic-response-number"><?php echo $this->escape($topic->amount_messages); ?> réponses</div>
                </div>
                <div class="topic-date"><?php echo $this->escape($topic->date);?></div>
            </div>
        </div>
    <?php $i++; endforeach; ?>
</div>