<div id="favtags">
    <ul id="favlist">
    <?php
        foreach($this->favTags as $fav) :
    ?>
        <li class="favorited-style">
            <a href="<?php echo $this->url(array(
                                                'controller'=>'topic',
                                                'action'=>'tag',
                                                'name'=> $this->escape($fav->name)
                                            )); ?>
                           " class="favorited-<?php echo $fav->tags_tagId; ?>"><?php echo $this->escape($fav->name);?></a>
           <a href="<?php echo $this->url(array(
                                                'controller'=>'tag',
                                                'action'=>'favorite',
                                                'tag'=> $this->escape($fav->tags_tagId)
                                            )); ?>" class="close2">x</a>
        </li>
     <?php endforeach; ?>
    </ul>
</div>

<div id="topics">
    <?php $i=0;
    foreach($this->topics as $topic) : ?>
        <div class="topic">
            <div class="subject">
                <span class="topic_subject"><a href="<?php echo $this->url(array(
                                            'controller'=>'topic',
                                            'action'=>'show',
                                            'topic'=>$this->escape($topic->topicId)
                                        )); ?>
                   "><?php echo $this->escape($topic->title);?></a></span>
            <span class="topic_vote"><?php echo $this->escape($topic->vote);?></span>
            <span class="topic_response_number"><?php echo '5'; ?></span>
            <span class="topic_date"><?php echo $this->escape($topic->date);?></span>
            </div>
            
            <div class="tags">
                Tags
                <?php
                foreach($this->$i as $tag) : ?>
                <a href="<?php echo $this->url(array(
                                            'controller'=>'topic',
                                            'action'=>'tag',
                                            'name'=> $this->escape($tag->name)
                                        )); ?>
                   "><?php echo $this->escape($tag->name); ?></a>

                <?php echo $this->favoriteTag($this->escape($tag->tag_tagId),'1');
                endforeach; ?>
            </div>
        </div>
    <?php $i++; endforeach; ?>
</div>