<?php 
$this->headTitle('Calendrier des évènements');
echo $this->doctype() . PHP_EOL; 
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="pragma" content="no-cache" />
        <?php echo $this->headMeta()->toString('		') . PHP_EOL; ?>
        <meta name="robots" content="index,follow" />

        <?php
        echo $this->headTitle()->toString('		') . PHP_EOL;
        echo $this->headLink()
                    ->prependStylesheet('/css/excite-bike/jquery-ui-1.8.17.custom.css')
                    ->appendStylesheet('/css/scheduler/dhtmlxscheduler_glossy.css');
        
            $this->headScript()->prependFile($this->baseUrl().'/js/scheduler/locale_fr.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/scheduler/dhtmlxscheduler_tooltip.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/scheduler/dhtmlxscheduler_serialize.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/scheduler/dhtmlxscheduler.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/jquery-ui-1.8.16.custom.min.js'); 
            echo $this->headScript()->prependFile($this->baseUrl().'/js/jquery-1.7.1.min.js');
        ?>
    </head>

<style type="text/css" media="screen">
	html, body{
		margin:0px;
		padding:0px;
		height:100%;
		overflow:hidden;
                font-family: "Helvetica Nueue", Arial;
	}
        a {
            color: #fff;
            text-decoration: none;
        }
        .link{
            padding: 5px;
        }
        .link:hover {
            color: #fff;
            background-color: #019428;
            padding: 5px;
            border-radius: 5px;
        }
        .table-top{
            width: 800px;
        }
	.dhx_cal_navline input{
		width:80px;
		position:absolute;
		top:1px;
		font-family:Tahoma;
		font-weight:8pt;
	}
        
        .help-event-link {
            cursor: pointer;
        }
        
        #dialog-help-events ul li {
            padding-bottom: 10px;
            font-size: 0.87em;
        }
        
        .event-top {
            background: url(../images/bandeau.jpg) repeat-y scroll center top black;
            width: 100%;
        }
</style>


<script type="text/javascript" charset="utf-8">
	function init() {
                var userId = <?php echo $this->escape($this->userId); ?>;
                
		scheduler.config.xml_date="%Y-%m-%d %H:%i";
		scheduler.config.prevent_cache = true;
		
		scheduler.config.lightbox.sections=[	
			{name:"description", height:130, map_to:"text", type:"textarea" , focus:true},
			{name:"location", height:43, type:"textarea", map_to:"details" },
			{name:"time", height:72, type:"time", map_to:"auto"}
		]
		scheduler.config.first_hour=9;
		scheduler.locale.labels.section_location="Location";
		//scheduler.config.details_on_create=true;
		//scheduler.config.details_on_dblclick=true;
		
		scheduler.init('scheduler_here', null,"month");
		scheduler.setLoadMode("month");
		scheduler.load("../../../../../../js/scheduler/events.php");
                
		var dp = new dataProcessor("../../../../../../js/scheduler/events.php");
		dp.init(scheduler);
                
                if(parseInt(userId) == 0)
                    scheduler.config.readonly = true;
                else
                {
                    scheduler.attachEvent("onEventAdded", function(event_id, event_object){
                        event_object.user_id = userId;
                    });

                    scheduler.attachEvent("onBeforeDrag", function (event_id, mode, native_event_object){
                       return check(event_id, userId);
                    });

                    scheduler.attachEvent("onClick", function (event_id, native_event_object){
                       return check(event_id, userId);
                    });

                    scheduler.attachEvent("onDblClick", function (event_id, native_event_object){
                       return check(event_id, userId);
                    });

                    var format=scheduler.date.date_to_str("%d-%m-%Y %H:%i"); 
                    scheduler.templates.tooltip_text = function(start,end,event) {
                            return "<b>Evèn.:</b> "+event.text+"<br/><b>Date début:</b> "+format(start)+"<br/><b>Date fin:</b> "+format(end)+"<br/><b>Lieu:</b> "+event.details;
                    };
                }
                
                dialogAlertDocument();
	}
        
        function check(event_id, userId)
        {
           var ev = scheduler.getEvent(event_id);
           if(typeof ev != "undefined")
           {
               if(typeof ev.user_id != "undefined")
               {
                   if(parseInt(ev.user_id) != userId)
                       return false; 
               }
           }
           return true;
        }
        
        function dialogAlertDocument()
        {
            $('#dialog-help-events').dialog({
                autoOpen: false,
                height: 415,
                width: 700,
                modal: true,
                buttons: {
                        Fermer: function() {
                                $( this ).dialog('close');
                        }
                },
                close: function() {
                        //allFields.val( "" ).removeClass( "ui-state-error" );
                }
            });

            $('.help-event-link').click(function(e) {
                e.preventDefault();
                $('#dialog-help-events').dialog('open');
            });
        }
</script>

<body onload="init();">
    <div class="event-top">
        <table class="table-top">
            <tbody>
                <tr>
                    <td>
                        <a href="<?php
                            echo $this->url(array(
                                'module' => 'default',
                                'controller' => 'index',
                                'action' => 'index'
                            ), 'default', true);
                            ?>"><img src="/images/logo.gif" height="50"/>
                        </a>
                    </td>
                    <td>
                        <?php if(isset($this->backUrl)) : ?>
                        <a class="link" href="<?php
                            echo $this->backUrl; ?>">Revenir en arrière
                        </a>
                        <?php else : ?>
                        <a class="link" href="<?php
                            echo $this->url(array(
                                'module' => 'default',
                                'controller' => 'index',
                                'action' => 'index'
                            ), 'default', true);
                            ?>">Revenir en arrière
                        </a>
                        <?php endif; ?>
                    </td>
                    <td>
                        <a class="help-event-link link">Aide </a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
	
    <div id="scheduler_here" class="dhx_cal_container" style='width:100%; height:100%;'>
        <div class="dhx_cal_navline">
                <div class="dhx_cal_prev_button">&nbsp;</div>
                <div class="dhx_cal_next_button">&nbsp;</div>
                <div class="dhx_cal_today_button"></div>
                <div class="dhx_cal_date"></div>
                <div class="dhx_cal_tab" name="day_tab" style="right:204px;"></div>
                <div class="dhx_cal_tab" name="week_tab" style="right:140px;"></div>
                <div class="dhx_cal_tab" name="month_tab" style="right:76px;"></div>
        </div>
        <div class="dhx_cal_header">
        </div>
        <div class="dhx_cal_data">
        </div>		
    </div>
    
    <div id="dialog-help-events" title="Aide" style="display:none;">
        <ul>
            <li>Vous pouvez consulter les détails d'un évènement en passant la souris dessus</li>
            <li>Vous devez vous connecter pour créer un évènement</li>
            <li>Vous pouvez ajouter un évènement en double cliquant dans la zone où vous souhaitez le créer</li>
            <li>Vous pouvez modifier ou supprimer un évènement que vous avez créé</li>
            <li>Vous ne pouvez pas modifier ou supprimer un évènement créé par une autre personne</li>
            <li>Pour changer la date d'un évènement que vous avez créé, vous pouvez le déplacer en maintenant le bouton de la souris</li>
            <li>Pour étendre la durée d'un évènement que vous avez créé vous pouvez l'étirer par le bas (en vue Jour et Semaine)</li>
        </ul>
    </div>
</body>


