<?php $this->headTitle('Administration'); ?>

<h2>Bonjour <?php echo $this->escape($this->username); ?></h2>

<a href="<?php echo $this->url(array(), 'addNews', true) ?>">Ajouter une news</a><br />

<h3>API Mobile</h3>
<a href="<?php echo $this->url(array(), 'addsahabastory', true) ?>">Ajouter une histoire de sahaba</a><br />
                                
<a href="<?php echo $this->url(array(), 'addreminder', true) ?>">Ajouter un rappel</a><br />

<hr>
Histoires sahabas à publier :  <?php echo $this->escape($this->storyCount); ?>
<br>
Rappels à publier :  <?php echo $this->escape($this->reminderCount); ?>
<br>
<a class="btn" href="<?php echo $this->url(array(), 'publish'); ?>">
Envoyer sur mobiles
</a>