<?php $this->headTitle('World Prayer Times Policy'); ?>
<h1>World Prayer Times service privacy policy</h1>

<p>
    World Prayer Times app does not collect any information about you. 
    The app only stores your current location in your computer.
</p>

<p>This privacy policy is subject to change. 
    If you have any questions 
    feel free to contact me directly at postmaster@islamine.com
</p>

<p>
Copyright © 2013 World Prayer Times. All rights reserved.
</p>