<?php
/**
 * Default Layout
 *
 * @author
 * @version
 */
echo $this->doctype() . PHP_EOL;
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="pragma" content="no-cache" />
        <?php echo $this->headMeta()->toString('		') . PHP_EOL; ?>
        <meta name="robots" content="index,follow" />

        <?php
        echo $this->headTitle()->toString('		') . PHP_EOL;
        echo $this->headLink()
                //http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css
                    ->prependStylesheet('/css/excite-bike/jquery-ui-1.8.17.custom.css')
                    ->appendStylesheet('/css/tagit/jquery.tagit.css')
                    ->appendStylesheet('/css/bootstrap.css')
                    ->appendStylesheet('/css/main.css')
                    ->appendStylesheet('/css/forum_orange.css')
                    ->appendStylesheet('/css/form.css');
        
            $this->headScript()->prependFile($this->baseUrl().'/js/ckfinder/ckfinder.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/ckeditor/ckeditor.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/forum.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/base.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/tagit/tag-it.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/jquery-ui-1.8.16.custom.min.js'); 
            echo $this->headScript()->prependFile($this->baseUrl().'/js/jquery-1.7.1.min.js');
            //$this->headScript()->prependFile("http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"); 
            //echo $this->headScript()->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js');
        ?>
        <!--[if IE 8]>
            <?php 
                echo $this->headLink()->appendStylesheet('/css/ie8.css');
            ?>
        <![endif]-->
        <script type="text/Javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-37498192-1']);
            _gaq.push(['_trackPageview']);

            (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>
    </head>
    <body>
        <noscript>
            <div id="noscript-padding">
            </div>
        </noscript>
        
        <?php echo $this->layout()->privilegeNotifPadding; ?>
        
        <div>
            <div id="bg-header-top"></div>
            <div id="bg-header-bottom"></div>
        </div>
        
        <div class="main">
            <div class="header">
                    <div class="logo">
                        <a href="<?php
        echo $this->url(array(
            'module' => 'default',
            'controller' => 'index',
            'action' => 'index'
        ), 'default', true);
        ?>">Islamine</a>
                    </div>
                <div id="user-top">
                    <?php echo $this->login(); ?>
                    <?php //echo $this->layout()->notifications; ?>
                </div>
                <div class="clr"></div>
                <div id="nav">
                        <ul>
                            <li><a href="<?php echo $this->url(array(
                                            'controller' => 'conference',
                                            'action' => 'index'
                                        ), 'default', true) ?>">Evènements</a></li>
                            
                            <li><a href="<?php echo $this->url(array(
                                            'controller' => 'article',
                                            'action' => 'index'
                                        ), 'default', true) ?>">Articles</a></li>
                            
                            <li><a href="<?php echo $this->url(array(
                                        ), 'indexForum', true) ?>">Forum</a></li>
                            
                            <li><a href="">Annonces</a></li>
                            
                            <li><a href="">Membres</a></li>
                            
                            <li><a href="">Contact</a></li>
                        </ul>
                    </div>
            </div>
            
            <div id="forum_nav">
                <ul>
                    <li><a href="<?php echo $this->url(array(
                                        'module' => 'forum',
                                        'controller' => 'topic',
                                        'action' => 'add'
                                        ), 'default', true) ?>"><span>Nouveau Topic</span></a></li>
                    
                    <li><a href="<?php echo $this->url(array(), 'showTags', true) ?>"><span>Mots-clés</span></a></li>
                    
                    <li><a href="<?php echo $this->url(array(
                                        ), 'faqForum', true) ?>"><span>FAQ</span></a></li>
                    
                    <li><a href="<?php echo $this->url(array(
                                        ), 'rulesForum', true) ?>"><span>Règles du forum</span></a></li>
                </ul>

            </div>
            <div class="clr"></div>
            
            <div id="partner">
                <img src="/images/banner.png" alt="banner" />
            </div>
            
            <!--<div id="sidebar-left">
                <div class="module">
                    Trier par<br />
                    Activité<br />
                    Votes<br />
                   <input type="radio" />Mois<br />
                    <input type="radio" />Semaine<br />
                </div>
            </div>-->
            
           
            
            
            <div id="content">
                <div id="forum-content">
                <?php
                echo $this->layout()->content . PHP_EOL;
                ?>
                </div>
                
                 <div id="sidebar-right">
                     <div class="forum-search">
                         <?php
                            echo new Forum_Form_Search();
                         ?>
                     </div>
                    <div class="module">
                        <?php echo $this->layout()->module_sort; ?>
                    </div>

                     <div class="module">
                        <?php echo $this->layout()->module_favtags; ?>
                    </div>

                    <div class="module">
                        <?php echo $this->layout()->module_description; ?>
                    </div>

                    <div class="modulep">
                        <p class="partage">PartageIslam</p>
                        <p>Vous avez des fichiers sur l'islam que vous voulez faire partager aux autre ?</p>
                        <p>Envoyez-les nous, et nous les publierons sur le site !</p>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="clr"></div>
        <div class="footer">
            <div class="footer-content">
                <p>Copyright © 2012</p>
                <p>
                    <a href="#">Sitemap</a> | 
                    <a href="#">Contact</a> | 
                    <a href="#">Mentions légales</a> | 
                    <a href="#">Flux RSS</a>
                </p>
            </div>
        </div>
        
        <?php echo $this->layout()->privilegeNotifications; ?>

        
        <noscript>
            <div id="notify-message-script">
                <span>Islamine fonctionne mieux avec JavaScript activé</span>
            </div>
        </noscript>
        
    </body>
</html>