<?php
/**
 * Default Layout
 *
 * @author
 * @version
 */
echo $this->doctype() . PHP_EOL;
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="pragma" content="no-cache" />
        <?php echo $this->headMeta()->toString('		') . PHP_EOL; ?>
        <meta name="robots" content="index,follow" />

        <?php
          echo $this->headTitle()->toString('		') . PHP_EOL;
          echo $this->headLink()
                    ->prependStylesheet('/css/excite-bike/jquery-ui-1.8.17.custom.css')
                    ->appendStylesheet('/css/bootstrap.css')
                    ->appendStylesheet('/css/feature-carousel.css')
                    ->appendStylesheet('/css/main.css');
        
            $this->headScript()->prependFile($this->baseUrl().'/js/base.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/tagit/tag-it.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/jquery.featureCarousel.min.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/jquery-ui-1.8.16.custom.min.js'); 
            echo $this->headScript()->prependFile($this->baseUrl().'/js/jquery-1.7.1.min.js');
        ?>
        <!--[if IE 8]>
            <?php 
                echo $this->headLink()->appendStylesheet('/css/ie8.css');
            ?>
        <![endif]-->
        <script type="text/javascript">
            $(document).ready(function() {
                var carousel = $("#carousel").featureCarousel({
                    autoPlay: 10000,
                    largeFeatureWidth: 450,
                    largeFeatureHeight: 230,
                    smallFeatureWidth: 225,
                    smallFeatureHeight: 115,
                    trackerSummation: false
                });
            });
            
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-37498192-1']);
            _gaq.push(['_trackPageview']);

            (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>
    </head>
    <body <?php echo $this->layout()->class; ?>>
        <noscript>
            <div id="noscript-padding">
            </div>
        </noscript>
        
        <?php echo $this->layout()->privilegeNotifPadding; ?>
        
        <div>
            <div id="bg-header-top"></div>
            <div id="bg-header-bottom"></div>
        </div>
        
        <div class="main">
            <div class="header">
                <div class="logo">
                    <a href="<?php
                        echo $this->url(array(
                            'module' => 'default',
                            'controller' => 'index',
                            'action' => 'index'
                        ), 'default', true);
                        ?>"><img src="/images/logo2.gif"/>
                    </a>
                </div>
                <div id="user-top">
                    <?php echo $this->login(); ?>
                </div>
                <div class="clr"></div>
                <div id="nav">
                    <ul>
                        <li><a href="<?php echo $this->url(array(
                                    ), 'news', true) ?>"
                                title="Les news d'Islamine">News</a></li>
                                
                        <li class="nav-index-2"><a href="<?php echo $this->url(array(
                                    ), 'docList', true) ?>"
                                title="Liste des documents (textes, audios, vidéos) envoyés par les membres">Documents</a>
                            <?php echo $this->submenu(); ?>
                        </li>

                        <li><a href="<?php echo $this->url(array(
                                        'controller' => 'event',
                                        'action' => 'index'
                                    ), 'default', true) ?>"
                                    title="Evènements en rapport avec l'Islam (conférences...)">Evènements</a></li>

                        <li><a href="<?php echo $this->url(array(
                                        'controller' => 'user',
                                        'action' => 'list'
                                    ), 'default', true) ?>"
                                title="Liste des membres">Membres</a></li>

                    </ul>
                </div>
            </div>
            
            <div class="clr"></div>
            <div id="partner">
            </div>
            <div id="content">
                <div class="index-content">
                    <?php
                    echo $this->layout()->content . PHP_EOL;
                    ?>
                </div>
            </div>
        </div>
        
        <div class="clr"></div>
        <div class="footer">
            <div class="footer-content">
                <p>Copyright © 2012</p>
                <p>
                    <a href="<?php echo $this->url(array(
                                    ), 'faq', true) ?>">FAQ</a> | 
                    <a href="#">Sitemap</a> | 
                    <a href="<?php echo $this->url(array(
                                    ), 'contact', true) ?>">Contact</a> | 
                    <a href="<?php echo $this->url(array(
                                        'controller' => 'index',
                                        'action' => 'copyright'
                                    ), 'default', true) ?>">Mentions légales</a> | 
                    <a href="#">Flux RSS</a>
                </p>
            </div>
        </div>
        
        <?php echo $this->layout()->privilegeNotifications; ?>

        <noscript>
            <div id="notify-message-script">
                <span>Islamine fonctionne mieux avec JavaScript activé</span>
            </div>
        </noscript>
    </body>
</html>