<?php
/**
 * Default Layout
 *
 * @author
 * @version
 */
echo $this->doctype() . PHP_EOL;
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="pragma" content="no-cache" />
        <?php echo $this->headMeta()->toString('		') . PHP_EOL; ?>
        <meta name="robots" content="index,follow" />

        <?php
          echo $this->headTitle()->toString('		') . PHP_EOL;
          echo $this->headLink()
                    ->prependStylesheet('/css/excite-bike/jquery-ui-1.8.17.custom.css')
                    ->appendStylesheet('/css/tagit/jquery.tagit.css')
                    ->appendStylesheet('/css/bootstrap.css')
                    ->appendStylesheet('/css/main.css')
                    ->appendStylesheet('/css/form.css');
        
            $this->headScript()->prependFile($this->baseUrl().'/js/ckfinder/ckfinder.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/ckeditor/ckeditor.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/library.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/base.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/tagit/tag-it.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/jquery-ui-1.8.16.custom.min.js'); 
            echo $this->headScript()->prependFile($this->baseUrl().'/js/jquery-1.7.1.min.js');
        ?>
    </head>
    <body>
        <noscript>
            <div id="noscript-padding">
            </div>
        </noscript>
        
        <?php echo $this->layout()->privilegeNotifPadding; ?>
        
        <div>
            <div id="bg-header-top"></div>
            <div id="bg-header-bottom"></div>
        </div>
        
        <div class="main">
            <div class="header">
                <div class="logo">
                    <a href="<?php
                        echo $this->url(array(
                            'module' => 'default',
                            'controller' => 'index',
                            'action' => 'index'
                        ), 'default', true);
                        ?>"><img src="/images/logo.jpg" height="50"/>
                    </a>
                </div>
                <div id="user-top">
                    <?php echo $this->login(); ?>
                </div>
                <div class="clr"></div>
                <div id="nav">
                    <ul>
                        <li><a href="<?php echo $this->url(array(
                                        'controller' => 'event',
                                        'action' => 'index'
                                    ), 'default', true) ?>">Evènements</a></li>

                        <li><a href="<?php echo $this->url(array(
                                        'controller' => 'article',
                                        'action' => 'index'
                                    ), 'default', true) ?>">Articles</a></li>

                        <li><a href="<?php echo $this->url(array(
                                    ), 'indexForum', true) ?>">Forum</a></li>

                        <li><a href="">Annonces</a></li>

                        <li><a href="<?php echo $this->url(array(
                                        'controller' => 'user',
                                        'action' => 'list'
                                    ), 'default', true) ?>">Membres</a></li>

                        <li><a href="">Contact</a></li>
                    </ul>
                </div>
            </div>
            
            <div class="clr"></div>
            <div id="partner">
                <img src="/images/banner.png" alt="banner" />
            </div>
            <div id="content">
                <div class="library-content">
                    <?php
                    echo $this->layout()->content . PHP_EOL;
                    ?>
                </div>
                <div id="sidebar-right">
                     <div class="forum-search">
                         <?php
                            echo new Forum_Form_Search();
                         ?>
                     </div>

                     <div class="module">
                        <?php echo $this->layout()->module_favtags; ?>
                     </div>

                    <div class="module">
                        <?php echo $this->layout()->module_description; ?>
                    </div>

                    <div class="modulep">
                        <p class="partage">PartageIslam</p>
                        <p>Vous avez des fichiers sur l'islam que vous voulez faire partager aux autre ?</p>
                        <p>Envoyez-les nous, et nous les publierons sur le site !</p>
                    </div>
                </div>
                        <!--<ul>
                            <li>
                                <div id="search" >
                                    <form method="get" action="#">
                                    <div>
                                        <input type="text" name="s" id="search-text" value="" />
					<input type="submit" id="search-submit" value="Go" />
                                    </div>
                                    </form>
				</div>
				<div style="clear: both;">&nbsp;</div>
                            </li>
                            <li>
                                <?php foreach($this->layout()->sidebar as $category => $articles) : ?>
                                
                                <div class="category"><?php echo $category; ?></div>
                                    <ul>
                                    <?php foreach($articles as $article) : ?>
                                        <li><a href="<?php echo $this->url(array(
                                            'controller' => 'article',
                                            'action' => 'show',
                                            'id' => $article->id
                                        )) ?>"><?php echo $article->title ?></a></li>
                                    <?php  endforeach; ?>
                                    </ul>
                               <?php endforeach;
                                ?>
                            </li>
			</ul>-->
            </div>
        </div>
        
        <div class="clr"></div>
        <div class="footer">
            <div class="footer-content">
                <p>Copyright © 2012</p>
                <p>
                    <a href="#">Sitemap</a> | 
                    <a href="#">Contact</a> | 
                    <a href="<?php echo $this->url(array(
                                        'controller' => 'index',
                                        'action' => 'copyright'
                                    ), 'default', true) ?>">Mentions légales</a> | 
                    <a href="#">Flux RSS</a>
                </p>
            </div>
        </div>
        
        <?php echo $this->layout()->privilegeNotifications; ?>

        <noscript>
            <div id="notify-message-script">
                <span>Islamine fonctionne mieux avec JavaScript activé</span>
            </div>
        </noscript>
    </body>
</html>