<?php
/**
 * Default Layout
 *
 * @author
 * @version
 */
echo $this->doctype() . PHP_EOL;
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="pragma" content="no-cache" />
        <?php echo $this->headMeta()->toString('		') . PHP_EOL; ?>
        <meta name="robots" content="index,follow" />

        <?php
          echo $this->headTitle()->toString('		') . PHP_EOL;
          echo $this->headLink()
                    ->prependStylesheet('/css/excite-bike/jquery-ui-1.8.17.custom.css')
                    ->appendStylesheet('/css/tagit/jquery.tagit.css')
                    ->appendStylesheet('/css/bootstrap.css')
                    ->appendStylesheet('/css/main.css')
                    ->appendStylesheet('/css/form.css');
        
            $this->headScript()->prependFile($this->baseUrl().'/js/ckfinder/ckfinder.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/ckeditor/ckeditor.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/library.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/base.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/tagit/tag-it.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/jquery-ui-1.8.16.custom.min.js'); 
            echo $this->headScript()->prependFile($this->baseUrl().'/js/jquery-1.7.1.min.js');
        ?>
        <!--[if IE 8]>
            <?php 
                echo $this->headLink()->appendStylesheet('/css/ie8.css');
            ?>
        <![endif]-->
        <script type="text/Javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-37498192-1']);
            _gaq.push(['_trackPageview']);

            (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>
    </head>
    <body>
        <noscript>
            <div id="noscript-padding">
            </div>
        </noscript>
        
        <?php echo $this->layout()->privilegeNotifPadding; ?>
        
        <div>
            <div id="bg-header-top"></div>
            <div id="bg-header-bottom"></div>
        </div>
        
        <div class="main">
            <div class="header">
                <div class="logo">
                    <a href="<?php
                        echo $this->url(array(
                            'module' => 'default',
                            'controller' => 'index',
                            'action' => 'index'
                        ), 'default', true);
                        ?>"><img src="/images/logo2.gif" alt="Islamine" />
                    </a>
                </div>
                <div id="user-top">
                    <?php echo $this->login(); ?>
                </div>
                <div class="clr"></div>
                <div id="nav">
                    <ul>
                        <li><a href="<?php echo $this->url(array(
                                    ), 'news', true) ?>"
                                title="Les news d'Islamine">News</a></li>
                                
                        <li class="nav-index-2"><a href="<?php echo $this->url(array(
                                    ), 'docList', true) ?>"
                                title="Liste des documents (textes, audios, vidéos) envoyés par les membres">Documents</a>
                                <?php echo $this->submenu(); ?>
                        </li>

                        <li><a href="<?php echo $this->url(array(
                                        'controller' => 'event',
                                        'action' => 'index'
                                    ), 'default', true) ?>"
                                    title="Evènements en rapport avec l'Islam (conférences...)">Evènements</a></li>

                        <li><a href="<?php echo $this->url(array(
                                        'controller' => 'user',
                                        'action' => 'list'
                                    ), 'default', true) ?>"
                                title="Liste des membres">Membres</a></li>

                    </ul>
                </div>
            </div>
            
            <div class="clr"></div>
            <div id="partner">
<!--                <img src="/images/banner.png" alt="banner" />-->
            </div>
            <div id="content">
                <div class="library-content">
                    <?php
                    echo $this->layout()->content . PHP_EOL;
                    ?>
                </div>
                <div id="sidebar-right">
                    
                     <div class="document-search">
                         <?php
                            echo new Default_Form_SearchDocument();
                         ?>
                     </div>
                    
                    <div class="module">
                        <?php echo $this->layout()->moduleNews; ?>
                     </div>

                     <div class="module">
                        <?php echo $this->layout()->module_favtags; ?>
                     </div>

                    <div class="modulep">
                        <h4>PartageIslam</h4>
                        <p>Vous avez des fichiers sur l'islam que vous voulez partager avec les autres ?</p>
                        <p>Uploadez-les sur un site et créez un document !</p>
                    </div>
                    
                    <div class="modulep">
                        <h4>Feedback</h4>
                        <p>Vous avez des idées ou des améliorations à nous proposer pour le site ?</p>
                        <p>N'hésitez pas à <a href="<?php echo $this->url(array(
                                    ), 'contact', true) ?>">nous contacter</a></p>
                    </div>
                    
                    <div class="modulep2">
                        <p class="partage">Attention</p>
                        <p>Merci de vérifier les sources de ce que vous publiez</p>
                    </div>
                    
                </div>
                        <!--<ul>
                            <li>
                                <div id="search" >
                                    <form method="get" action="#">
                                    <div>
                                        <input type="text" name="s" id="search-text" value="" />
					<input type="submit" id="search-submit" value="Go" />
                                    </div>
                                    </form>
				</div>
				<div style="clear: both;">&nbsp;</div>
                            </li>
                            <li>
                                <?php foreach($this->layout()->sidebar as $category => $articles) : ?>
                                
                                <div class="category"><?php echo $category; ?></div>
                                    <ul>
                                    <?php foreach($articles as $article) : ?>
                                        <li><a href="<?php echo $this->url(array(
                                            'controller' => 'article',
                                            'action' => 'show',
                                            'id' => $article->id
                                        )) ?>"><?php echo $article->title ?></a></li>
                                    <?php  endforeach; ?>
                                    </ul>
                               <?php endforeach;
                                ?>
                            </li>
			</ul>-->
            </div>
        </div>
        
        <div class="clr"></div>
        <div class="footer">
            <div class="footer-content">
                <p>Copyright © 2013</p>
                <p>
                    <a href="<?php echo $this->url(array(
                                    ), 'faq', true) ?>">FAQ</a> | 
                    <a href="<?php echo $this->url(array(
                                    ), 'contact', true) ?>">Contact</a> | 
                    <a href="<?php echo $this->url(array(
                                        'controller' => 'index',
                                        'action' => 'copyright'
                                    ), 'default', true) ?>">Mentions légales</a> | 
                    <a href="#">Flux RSS</a>
                </p>
            </div>
        </div>
        
        <?php echo $this->layout()->privilegeNotifications; ?>

        <noscript>
            <div id="notify-message-script">
                <span>Islamine fonctionne mieux avec JavaScript activé</span>
            </div>
        </noscript>
    </body>
</html>