<?php
/**
 * Default Layout
 *
 * @author
 * @version
 */
echo $this->doctype() . PHP_EOL;
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="pragma" content="no-cache" />
        <?php echo $this->headMeta()->toString('		') . PHP_EOL; ?>
        <meta name="robots" content="index,follow" />

        <?php
        echo $this->headTitle()->toString('		') . PHP_EOL;
        echo $this->headLink()
                    ->appendStylesheet('/css/bootstrap.css')
                    ->appendStylesheet('/css/main.css')
                    ->appendStylesheet('/css/mosque.css');
        
            $this->headScript()->prependFile($this->baseUrl().'/js/markerclusterer.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/jquery.geocomplete.min.js');
            $this->headScript()->prependFile($this->baseUrl().'/js/jquery-ui-1.8.16.custom.min.js'); 
            echo $this->headScript()->prependFile($this->baseUrl().'/js/jquery-1.7.1.min.js');
        ?>
        <script src="http://maps.googleapis.com/maps/api/js?language=en&sensor=false&libraries=places"></script>
        <script>
          $(function(){

            $("#find").click(function(){
              $("#geocomplete").trigger("geocode");
            });
            
          });
        </script>
    </head>
    <body>
        <noscript>
            <div id="noscript-padding">
            </div>
        </noscript>
        <div class="event-top">
            <table class="table-top">
                <tbody>
                    <tr>
                        <td>
                            <a href="<?php
                                echo $this->url(array(
                                    'module' => 'default',
                                    'controller' => 'index',
                                    'action' => 'index'
                                ), 'default', true);
                                ?>"><img src="/images/logo.gif" height="50"/>
                            </a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
              
        <div id="mosque-content">
        <?php
            echo $this->layout()->content . PHP_EOL;
        ?>
        </div>
         <div class="contact-link">
            <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'contact'), 'default', true) ?>">Reporter un bug - Contact</a>
         </div>       
        <noscript>
            <div id="notify-message-script">
                <span>Islamine fonctionne mieux avec JavaScript activé</span>
            </div>
        </noscript>
    </body>
</html>