<?php $this->headTitle('Add a mosque'); ?>
<div id="mosque-form">
     
    <?php 
    echo $this->form;
    ?>

    <div id="map_canvas"></div>
</div>
<script>
    $(function(){
                     
              var options = {
                map: "#map_canvas",
                details: "form",
                markerOptions: { disabled: true },
                types: ["geocode", "establishment"]
                  
              };
              
            $("#geocomplete").geocomplete(options);
            
    });
</script>