<?php $this->headTitle('Enregistrer une mosquée'); ?>
<div id="mosque-form">
     
    <?php
    if($this->error != null)
        echo '<div class="help-error">'.$this->error.'</div>';
    
    echo $this->form;
    ?>

    <div id="map-canvas"></div>
    
    <div id="error-dialog" title="Erreur" style="display:none;">
        L'adresse n'est pas valide ou n'a pas été reconnue sur la carte
    </div>
</div>
<script>
$(function(){       
    var options = {
        map: "#map-canvas",
        details: "form",
        types: ["geocode", "establishment"]
    };
    
    $('#error-dialog').dialog({
                autoOpen: false,
                height: 110,
                width: 300,
                modal: true
            });
    
    $("#geocomplete").geocomplete(options);
});
</script>