<?php $this->headTitle('Enregistrer une mosquée'); ?>
<div id="mosque-form">
     
    <?php
    if($this->error != null)
        echo '<div class="help-error">'.$this->error.'</div>';
    
    echo $this->form;
    ?>

    <div id="map-canvas"></div>
</div>
<script>
$(function(){       
    var options = {
        map: "#map-canvas",
        details: "form",
        types: ["geocode", "establishment"]
    };
    
    $("#geocomplete").geocomplete(options);
    
    $("input[name='form_mosque_address']").change(function() {
        var geocomplete = $("#geocomplete");
        geocomplete.addClass('ui-autocomplete-loading');
        
        setTimeout(function(){
            var address = $("input[name='form_mosque_address']").val();
            var existing = $(".existing-mosques");
            if(address != ''){
                $.get("/mosque/byroute/" + address, function(data) {
                    geocomplete.removeClass('ui-autocomplete-loading');
                    var html = '<span class="title">Mosquées déjà existantes aux alentours</span>';
                    var mosques = JSON.parse(data);
                    mosques.length > 0 ? existing.show() : existing.hide();
                    for(var i = 0; i < mosques.length; i++) {
                        html += '<span class="mosque-name">' + mosques[i].name + '</span>' + mosques[i].address;
                        html += '<br />';
                    }
                    existing.html(html);
                });
            }
            else {
                geocomplete.removeClass('ui-autocomplete-loading');
                existing.hide();
            }
        }, 200);
    });
});
</script>